/**
 * Codemap context injection hook.
 *
 * Reads the root codemap.md (generated by the cartography skill) and injects
 * it into the agent's context via the experimental.chat.messages.transform hook.
 *
 * This gives agents automatic repository awareness without requiring manual
 * file reads, matching the behavior users expect from AGENTS.md-style files.
 */
import { existsSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import type { PluginInput } from '@opencode-ai/plugin';
import { log } from '../../utils/logger';

interface MessageInfo {
  role: string;
  agent?: string;
  sessionID?: string;
}

interface MessagePart {
  type: string;
  text?: string;
  [key: string]: unknown;
}

interface MessageWithParts {
  info: MessageInfo;
  parts: MessagePart[];
}

// Agents that benefit from codemap context
const CODEMAP_AGENTS = new Set(['orchestrator', 'explorer']);

// Cache codemap content per workspace directory
const codemapCache = new Map<string, { content: string; mtime: number }>();

function loadCodemap(workspaceDir: string): string | null {
  const codemapPath = join(workspaceDir, 'codemap.md');

  if (!existsSync(codemapPath)) {
    return null;
  }

  try {
    const stat = statSync(codemapPath);
    const cached = codemapCache.get(workspaceDir);

    // Return cached version if file hasn't changed
    if (cached && cached.mtime === stat.mtimeMs) {
      return cached.content;
    }

    const content = readFileSync(codemapPath, 'utf-8');
    codemapCache.set(workspaceDir, { content, mtime: stat.mtimeMs });
    log('[codemap-context] loaded codemap.md', { path: codemapPath });
    return content;
  } catch {
    return null;
  }
}

// Track which sessions have already received the codemap
const injectedSessions = new Set<string>();

export function createCodemapContextHook(ctx: PluginInput) {
  const workspaceDir = ctx.directory;

  return {
    'experimental.chat.messages.transform': async (
      _input: Record<string, never>,
      output: { messages: MessageWithParts[] },
    ): Promise<void> => {
      const { messages } = output;

      if (messages.length === 0) {
        return;
      }

      // Find the last user message
      let lastUserMessageIndex = -1;
      for (let i = messages.length - 1; i >= 0; i--) {
        if (messages[i].info.role === 'user') {
          lastUserMessageIndex = i;
          break;
        }
      }

      if (lastUserMessageIndex === -1) {
        return;
      }

      const lastUserMessage = messages[lastUserMessageIndex];

      // Only inject for codemap-aware agents (or main session with no agent)
      const agent = lastUserMessage.info.agent;
      if (agent && !CODEMAP_AGENTS.has(agent)) {
        return;
      }

      const sessionID = lastUserMessage.info.sessionID;
      if (!sessionID || injectedSessions.has(sessionID)) {
        return;
      }

      const codemap = loadCodemap(workspaceDir);
      if (!codemap) {
        return;
      }

      // Find the first text part
      const textPartIndex = lastUserMessage.parts.findIndex(
        (p) => p.type === 'text' && p.text !== undefined,
      );

      if (textPartIndex === -1) {
        return;
      }

      const originalText = lastUserMessage.parts[textPartIndex].text ?? '';

      // Inject codemap as context before the user's message
      lastUserMessage.parts[textPartIndex].text =
        `<repository_context>\n${codemap}\n</repository_context>\n\n---\n\n${originalText}`;

      injectedSessions.add(sessionID);
      log('[codemap-context] injected codemap into session', {
        sessionID,
        agent,
      });
    },
  };
}
