const ADJECTIVES = [
  "resilient",
  "luminous",
  "graceful",
  "vigilant",
  "serene",
  "fierce",
  "quiet",
  "bold",
  "steady",
  "ancient",
  "nimble",
  "radiant",
  "stalwart",
  "winding",
  "subtle",
  "brisk",
  "enduring",
  "hushed",
  "resolute",
  "valiant",
  "tempered",
  "candid",
  "crisp",
  "echoing",
  "silver",
  "golden",
  "granite",
  "verdant",
  "horizon",
  "lucid",
  "daring",
  "patient",
  "tidal",
  "humble",
  "sunlit",
  "starbound",
  "deep",
  "swift",
  "measured",
  "brave",
  "focused",
  "calm",
  "spiraled",
  "earnest",
  "hidden",
  "open",
  "kind",
  "clear",
  "rugged",
  "poised"
] as const;

const GERUNDS = [
  "forging",
  "weaving",
  "tracing",
  "binding",
  "carving",
  "drifting",
  "kindling",
  "mapping",
  "shaping",
  "threading",
  "charting",
  "guiding",
  "anchoring",
  "balancing",
  "building",
  "calibrating",
  "crafting",
  "focusing",
  "honing",
  "layering",
  "linking",
  "mending",
  "nurturing",
  "opening",
  "polishing",
  "refining",
  "seeding",
  "stitching",
  "tempering",
  "tuning",
  "unfolding",
  "bridging",
  "circling",
  "crossing",
  "deepening",
  "drawing",
  "framing",
  "gliding",
  "holding",
  "joining",
  "lifting",
  "marking",
  "paring",
  "rising",
  "scouting",
  "shielding",
  "smoothing",
  "stacking",
  "steadying",
  "watching"
] as const;

const NOUNS = [
  "compass",
  "anchor",
  "meridian",
  "beacon",
  "prism",
  "sentinel",
  "vessel",
  "keystone",
  "threshold",
  "lattice",
  "harbor",
  "horizon",
  "citadel",
  "cairn",
  "spire",
  "aperture",
  "canopy",
  "crossroad",
  "delta",
  "ember",
  "foundry",
  "gateway",
  "helm",
  "isotope",
  "junction",
  "kernel",
  "lantern",
  "matrix",
  "nexus",
  "orbit",
  "parallax",
  "quarry",
  "rampart",
  "signal",
  "tidemark",
  "uplink",
  "vector",
  "watchtower",
  "yardarm",
  "zenith",
  "atlas",
  "bastion",
  "current",
  "dock",
  "engine",
  "field",
  "grove",
  "hinge",
  "insight",
  "journey"
] as const;

// Math.random() returns [0, 1) per spec, so index is always in bounds.
function pickWord(words: readonly string[]): string {
  const index = Math.floor(Math.random() * words.length);
  return words[index];
}

/**
 * Generates a random three-word plan name (adjective-gerund-noun).
 * 50 x 50 x 50 = 125,000 combinations. No collision detection -
 * callers should verify uniqueness if needed.
 */
export function generatePlanName(): string {
  return `${pickWord(ADJECTIVES)}-${pickWord(GERUNDS)}-${pickWord(NOUNS)}`;
}
